# PANEL 2 multimapping dataframes created using groupby ID


## 2 versions of merged Ensembl fasta + xref IDs made in markdown D

### version 1, shared stableID_key {ENSG_ENST_ENSP}, (n=8861 stableID_keys and 3887 ukb IDs)
```
v85_fasta_merge_xref_8865IDs_3889xref.csv
v92_fasta_merge_xref_8865IDs_3889xref.csv
v94_fasta_merge_xref_8865IDs_3889xref.csv
v96_fasta_merge_xref_8865IDs_3889xref.csv
v97_fasta_merge_xref_8865IDs_3889xref.csv

```

### version 2, shared uniprot IDs (n=3953), diff total row count
```
v85_fasta_merge_xref_3955IDs_10188.csv
v92_fasta_merge_xref_3955IDs_10399.csv
v94_fasta_merge_xref_3955IDs_10616.csv
v96_fasta_merge_xref_3955IDs_10667.csv
v97_fasta_merge_xref_3955IDs_10568.csv

# all other releases, len of df = # unique ENSP and ENST in df

```

#### isoform count file from Uniprot ID mapping: 
**previously made in markdown : 19_09_04_DEPvsINDEP_v97versionID_IDmappingdat**
- UniprotIDMAPPING_isoformCount__labeledBefore_ENSPsource_3955unique entries.csv

In [1]:
import os
import sys
import pandas as pd
from statistics import stdev 

from IPython.display import display, HTML
pd.set_option('display.max_columns', None)
pd.options.display.max_seq_items = 2000
display(HTML("<style>.container {width:90% !important;}</style>"))

sys.path.append("/Users/mariapalafox/Desktop/Toolbox")
from all_funx import *

os.chdir("/Users/mariapalafox/Box Sync/CODE_DATA/dir_MAPpaper/TSV_UNIPROT_xref/MULTIMAPPING_IDs/")
print(os.listdir())

['ultimate_UKB_sequence_key_3953.csv', 'MISMAP2.0', 'v96_fasta_merge_xref_3953IDs_10663.csv', 'v92_fasta_merge_xref_8861IDs_3887.csv', 'v92_fasta_merge_xref_3953IDs_10395.csv', '.DS_Store', 'ALL_releases_list_stdev_ID_versions_3953.csv', 'v97_fasta_merge_xref_3953IDs_10564.csv', 'ENSEMBL_SEQ_v97_3953_UKBIDs.csv', 'Rmerge_MISMAP_sharedStableID_keyOnly_3887.csv', 'ENSEMBL_SEQ_v96_3953_UKBIDs.csv', 'SEQ_distance_UKBvsENSP', 'dict_3953_C_value_counts.csv', 'UKBID_3953set.csv', 'dict_3953_CK_value_counts.csv', 'v97_fasta_merge_xref_8861IDs_3887.csv', 'ENSEMBL_SEQ_v94_3953_UKBIDs.csv', 'dict_3953_K_value_counts.csv', 'ENSEMBL_SEQ_v85_3953_UKBIDs.csv', 'dict_with_CK_counts_3953.csv', 'ALL_releases_set_counts_ID_types_3953.csv', 'xref_files_3955', 'ENSEMBL_SEQ_v92_3953_UKBIDs.csv', 'UKBID_3887set.csv', 'v96_fasta_merge_xref_8861IDs_3887.csv', 'v94_fasta_merge_xref_8861IDs_3887.csv', 'v85_fasta_merge_xref_8861IDs_3887.csv', 'v85_fasta_merge_xref_3953IDs_10183.csv', 'v94_fasta_merge_xref_3953IDs

```python 
# before I dropped both Q8WUH1 (Church hill protein not well characterized) and Q8WUH1
v85 = pd.read_csv("v85_fasta_merge_xref_3955IDs_10188.csv")
v92 = pd.read_csv("v92_fasta_merge_xref_3955IDs_10399.csv")
v94 = pd.read_csv("v94_fasta_merge_xref_3955IDs_10616.csv")
v96 = pd.read_csv("v96_fasta_merge_xref_3955IDs_10667.csv")
v97 = pd.read_csv("v97_fasta_merge_xref_3955IDs_10568.csv")

shared85 = pd.read_csv("v85_fasta_merge_xref_8865IDs_3889xref.csv")
shared92 = pd.read_csv("v92_fasta_merge_xref_8865IDs_3889xref.csv")
shared94 = pd.read_csv("v94_fasta_merge_xref_8865IDs_3889xref.csv")
shared96 = pd.read_csv("v96_fasta_merge_xref_8865IDs_3889xref.csv")
shared97 = pd.read_csv("v97_fasta_merge_xref_8865IDs_3889xref.csv")
```

# dropping 2 IDs : Q9H1A7 & Q8WUH1

In [38]:
# now dropping other ID
v85 = pd.read_csv("v85_fasta_merge_xref_3954IDs_10187.csv")
v92 = pd.read_csv("v92_fasta_merge_xref_3954IDs_10398.csv")
v94 = pd.read_csv("v94_fasta_merge_xref_3954IDs_10615.csv")
v96 = pd.read_csv("v96_fasta_merge_xref_3954IDs_10666.csv")
v97 = pd.read_csv("v97_fasta_merge_xref_3954IDs_10567.csv")

shared85 = pd.read_csv("v85_fasta_merge_xref_8864IDs_3888xref.csv")
shared92 = pd.read_csv("v92_fasta_merge_xref_8864IDs_3888xref.csv")
shared94 = pd.read_csv("v94_fasta_merge_xref_8864IDs_3888xref.csv")
shared96 = pd.read_csv("v96_fasta_merge_xref_8864IDs_3888xref.csv")
shared97 = pd.read_csv("v97_fasta_merge_xref_8864IDs_3888xref.csv")

## create new columns for version number

```python
def split_version(df):
    pro = df["ENSPv"].str.split(".", n=1, expand=True)
    pro.columns = ['stable', 'pro_ver']
    ensp = pro['pro_ver'].astype(int)
    
    tx = df["ENSTv"].str.split(".", n=1, expand=True)
    tx.columns = ['stable', 'tx_ver']
    enst = tx['tx_ver'].astype(int)
    
    gen = df["ENSGv"].str.split(".", n=1, expand=True)
    gen.columns = ['stable', 'gen_ver']
    ensg = gen['gen_ver'].astype(int)
    
    final = pd.concat([df, ensp, enst, ensg], axis=1)
    return final

v85 = split_version(v85)
v92 = split_version(v92)
v94 = split_version(v94)
v96 = split_version(v96)
v97 = split_version(v97)

# same for shared ENSG_ENST_ENSP version
shared85 = split_version(shared85)
shared92 = split_version(shared92)
shared94 = split_version(shared94)
shared96 = split_version(shared96)
shared97 = split_version(shared97)



resaving with new columns
v85.to_csv("v85_fasta_merge_xref_3955IDs_10188.csv", index=False)
v92.to_csv("v92_fasta_merge_xref_3955IDs_10399.csv", index=False)
v94.to_csv("v94_fasta_merge_xref_3955IDs_10616.csv", index=False)
v96.to_csv("v96_fasta_merge_xref_3955IDs_10667.csv", index=False)
v97.to_csv("v97_fasta_merge_xref_3955IDs_10568.csv", index=False)

shared85.to_csv("v85_fasta_merge_xref_8865IDs_3889xref.csv", index=False)
shared92.to_csv("v92_fasta_merge_xref_8865IDs_3889xref.csv", index=False)
shared94.to_csv("v94_fasta_merge_xref_8865IDs_3889xref.csv", index=False)
shared96.to_csv("v96_fasta_merge_xref_8865IDs_3889xref.csv", index=False)
shared97.to_csv("v97_fasta_merge_xref_8865IDs_3889xref.csv", index=False)
```

In [39]:
v85.head(3)

ENSPv             ENSP              ENSTv             ENST  \
0  ENSP00000313454.4  ENSP00000313454  ENST00000322244.5  ENST00000322244   
1  ENSP00000399234.2  ENSP00000399234  ENST00000420827.2  ENST00000420827   
2  ENSP00000251527.5  ENSP00000251527  ENST00000251527.5  ENST00000251527   

                ENSGv             ENSG  Length  \
0   ENSG00000033178.8  ENSG00000033178    1052   
1   ENSG00000033178.8  ENSG00000033178     389   
2  ENSG00000117868.11  ENSG00000117868     893   

                                         proSequence  \
0  MEGSEPVAAHQGEEASCSSWGTGSTNKNLPIMSTASVEIDDALYSR...   
1  MEGSEPVAAHQGEEASCSSWGTGSTNKNLPIMSTASVEIDDALYSR...   
2  MTPPSRAEAGVRRSRVPSEGRWRGAEPPGISASTQPASAGRAARHC...   

                                      stableID_key    xref  pro_ver  tx_ver  \
0  ENSG00000033178_ENST00000322244_ENSP00000313454  A0AVT1        4       5   
1  ENSG00000033178_ENST00000420827_ENSP00000399234  A0AVT1        2       2   
2  ENSG00000117868_ENST00000251527_ENSP00000251527  A0FGR8        5       5   

   gen_ver  
0        8  
1        8  
2       11

In [40]:
shared85.head(3)

ENSPv             ENSP              ENSTv             ENST  \
0  ENSP00000363937.5  ENSP00000363937  ENST00000374804.5  ENST00000374804   
1  ENSP00000363940.5  ENSP00000363940  ENST00000374807.5  ENST00000374807   
2  ENSP00000363944.3  ENSP00000363944  ENST00000374811.3  ENST00000374811   

                ENSGv             ENSG  Length  \
0  ENSG00000001497.12  ENSG00000001497     675   
1  ENSG00000001497.12  ENSG00000001497     717   
2  ENSG00000001497.12  ENSG00000001497     734   

                                         proSequence  \
0  MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...   
1  MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...   
2  MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...   

                                      stableID_key    xref  pro_ver  tx_ver  \
0  ENSG00000001497_ENST00000374804_ENSP00000363937  Q9Y4W2        5       5   
1  ENSG00000001497_ENST00000374807_ENSP00000363940  Q9Y4W2        5       5   
2  ENSG00000001497_ENST00000374811_ENSP00000363944  Q9Y4W2        3       3   

   gen_ver  
0       12  
1       12  
2       12

# PANEL 3 prep for mismap
**are all 3955 IDs and 3889 IDs contained in 3979 set previously used for mismap scoring???**

In [14]:
ls3955 = list(v85['xref'])
print(len(ls3955))
set3955 = set(ls3955)
print(len(set3955))

ls3889 = list(shared85['xref'])
set3889 = set(ls3889)
print(len(ls3889))
print(len(set3889))

10188
3955


In [21]:
df3979 = pd.read_csv("/Users/mariapalafox/Box Sync/CODE_DATA/dir_MAPpaper/TSV_UNIPROT_xref/IDs/uniprot3979_IDs.csv")
df3979.head(4)

entry
0  Q09666
1  P21333
2  O75369
3  Q15149

In [23]:
ls3979 = list(df3979.entry)
print(len(ls3979))

diffls = diffList(ls3955, ls3979)
diffls

diff2 = diffList(ls3889, ls3979)
diff2

3979
different number of IDs :  1


['Q9H1A7']

## Q9H1A7 previously dropped in mismap v1 due to redundant stable ID key in v85 xref file prior to filtering file. 
### dropping this ID from 3955 files and 3889 file making total -1. 
- see 19_09_11_Ensembl_versionIDs_IDENTITYproseq_MISMAP_SCORING.ipynb

In [25]:
v85 = v85[v85['xref'] != 'Q9H1A7']
v92 = v92[v92['xref'] != 'Q9H1A7']
v94 = v94[v94['xref'] != 'Q9H1A7']
v96 = v96[v96['xref'] != 'Q9H1A7']
v97 = v97[v97['xref'] != 'Q9H1A7']

shared85 = shared85[shared85['xref'] != 'Q9H1A7']
shared92 = shared92[shared92['xref'] != 'Q9H1A7']
shared94 = shared94[shared94['xref'] != 'Q9H1A7']
shared96 = shared96[shared96['xref'] != 'Q9H1A7']
shared97 = shared97[shared97['xref'] != 'Q9H1A7']

In [41]:
v85 = v85[v85['xref'] != 'Q8WUH1']
v92 = v92[v92['xref'] != 'Q8WUH1']
v94 = v94[v94['xref'] != 'Q8WUH1']
v96 = v96[v96['xref'] != 'Q8WUH1']
v97 = v97[v97['xref'] != 'Q8WUH1']

shared85 = shared85[shared85['xref'] != 'Q8WUH1']
shared92 = shared92[shared92['xref'] != 'Q8WUH1']
shared94 = shared94[shared94['xref'] != 'Q8WUH1']
shared96 = shared96[shared96['xref'] != 'Q8WUH1']
shared97 = shared97[shared97['xref'] != 'Q8WUH1']

In [43]:
fil = [v85, v92, v94, v96, v97]
for i in fil:
    print(len(set(i['ENSG'])))
    print(len(set(i['ENST'])))
    print(len(set(i['ENSP'])))
    print(len(set(i['xref'])))
    print()

4344
10183
10183
3953

4332
10395
10395
3953

4345
10612
10612
3953

4336
10663
10663
3953

4336
10564
10564
3953



In [44]:
### fil = [v85, v92, v94, v96, v97, shared85,shared92,shared94,shared96,shared97]
fil = [shared85,shared92,shared94,shared96,shared97]
for i in fil:
    print(len(set(i['ENSG'])))
    print(len(set(i['ENST'])))
    print(len(set(i['ENSP'])))
    print(len(set(i['xref'])))
    print()

4086
8861
8861
3887

4086
8861
8861
3887

4086
8861
8861
3887

4086
8861
8861
3887

4086
8861
8861
3887



**resaving post drop of 2 IDs final unique uniprot count now 3953 and 3887, updated MAPPING_tables**

In [45]:
v85.to_csv("v85_fasta_merge_xref_3953IDs_10183.csv", index=False)
v92.to_csv("v92_fasta_merge_xref_3953IDs_10395.csv", index=False)
v94.to_csv("v94_fasta_merge_xref_3953IDs_10612.csv", index=False)
v96.to_csv("v96_fasta_merge_xref_3953IDs_10663.csv", index=False)
v97.to_csv("v97_fasta_merge_xref_3953IDs_10564.csv", index=False)

shared85.to_csv("v85_fasta_merge_xref_8861IDs_3887xref.csv", index=False)
shared92.to_csv("v92_fasta_merge_xref_8861IDs_3887xref.csv", index=False)
shared94.to_csv("v94_fasta_merge_xref_8861IDs_3887xref.csv", index=False)
shared96.to_csv("v96_fasta_merge_xref_8861IDs_3887xref.csv", index=False)
shared97.to_csv("v97_fasta_merge_xref_8861IDs_3887xref.csv", index=False)

## make simple ID column file for new version of ukb ID sets [ n=3953 & 3887]

In [46]:
df3954 = v85['xref']
df3888 = shared85['xref']
df3954.drop_duplicates(inplace=True)
df3888.drop_duplicates(inplace=True)

print(df3954.shape)
print(df3888.shape)

df54 = pd.DataFrame(df3954)
df88 = pd.DataFrame(df3888)

print(df54.shape)
print(df88.shape)

df54.to_csv("UKBID_3953set.csv", index=False)
df88.to_csv("UKBID_3887set.csv", index=False)

(3953,)
(3887,)
(3953, 1)
(3887, 1)


---
---
---

---
---
---

# PANEL 2 Multimapping figure 
### with stable vs version IDs in ENSG, ENST, ENSP levels


## 2 versions
1. 3953 IDs in each release with different number of rows
2. 3887 IDs in each release with same number of 8861 STABLE ID key rows

In [24]:
v85 = pd.read_csv("v85_fasta_merge_xref_3953IDs_10183.csv")
v92 = pd.read_csv("v92_fasta_merge_xref_3953IDs_10395.csv")
v94 = pd.read_csv("v94_fasta_merge_xref_3953IDs_10612.csv")
v96 = pd.read_csv("v96_fasta_merge_xref_3953IDs_10663.csv")
v97 = pd.read_csv("v97_fasta_merge_xref_3953IDs_10564.csv")

In [2]:
v85share = pd.read_csv("v85_fasta_merge_xref_8861IDs_3887.csv")
v92share = pd.read_csv("v92_fasta_merge_xref_8861IDs_3887.csv")
v94share = pd.read_csv("v94_fasta_merge_xref_8861IDs_3887.csv")
v96share = pd.read_csv("v96_fasta_merge_xref_8861IDs_3887.csv")
v97share = pd.read_csv("v97_fasta_merge_xref_8861IDs_3887.csv")

In [29]:
all_3953 = pd.concat([v85,v92, v94, v96, v97])
describeMe(all_3953)

(52417, 13)
Index(['ENSPv', 'ENSP', 'ENSTv', 'ENST', 'ENSGv', 'ENSG', 'Length',
       'proSequence', 'stableID_key', 'xref', 'pro_ver', 'tx_ver', 'gen_ver'],
      dtype='object')
ENSPv           0
ENSP            0
ENSTv           0
ENST            0
ENSGv           0
ENSG            0
Length          0
proSequence     0
stableID_key    0
xref            0
pro_ver         0
tx_ver          0
gen_ver         0
dtype: int64


In [30]:
share_3887 = pd.concat([v85share,v92share, v94share, v96share, v97share])
describeMe(share_3887)

(44305, 13)
Index(['ENSPv', 'ENSP', 'ENSTv', 'ENST', 'ENSGv', 'ENSG', 'Length',
       'proSequence', 'stableID_key', 'xref', 'pro_ver', 'tx_ver', 'gen_ver'],
      dtype='object')
ENSPv           0
ENSP            0
ENSTv           0
ENST            0
ENSGv           0
ENSG            0
Length          0
proSequence     0
stableID_key    0
xref            0
pro_ver         0
tx_ver          0
gen_ver         0
dtype: int64


In [31]:
8861*5

44305

## create count frame from counting len of set's in each column

In [32]:
%%time

# diff number of rows but same number of IDs in each release

def setme(s):
    ls = list(s)
    finalset = set(ls)
    return finalset


# columns based on set of IDs or sequences from all releases
ENSP_all_3953 = all_3953.groupby('xref')['ENSP'].apply(setme)
ENSPv_all_3953 = all_3953.groupby('xref')['ENSPv'].apply(setme)
ENST_all_3953 = all_3953.groupby('xref')['ENST'].apply(setme)
ENSTv_all_3953 = all_3953.groupby('xref')['ENSTv'].apply(setme)
ENSG_all_3953 = all_3953.groupby('xref')['ENSG'].apply(setme)
ENSGv_all_3953 = all_3953.groupby('xref')['ENSGv'].apply(setme)
stableID_key_all_3953 = all_3953.groupby('xref')['stableID_key'].apply(setme)
proSequence_all_3953 = all_3953.groupby('xref')['proSequence'].apply(setme)

# concat
set_columns = pd.concat([ENSP_all_3953, ENSPv_all_3953, ENST_all_3953, ENSTv_all_3953, ENSG_all_3953, ENSGv_all_3953, stableID_key_all_3953, proSequence_all_3953], axis=1)

set_columns['count_ENSP'] = set_columns['ENSP'].apply(lambda x: len(x))
set_columns['count_ENSPv'] = set_columns['ENSPv'].apply(lambda x: len(x))
set_columns['count_ENST'] = set_columns['ENST'].apply(lambda x: len(x))
set_columns['count_ENSTv'] = set_columns['ENSTv'].apply(lambda x: len(x))
set_columns['count_ENSG'] = set_columns['ENSG'].apply(lambda x: len(x))
set_columns['count_ENSGv'] = set_columns['ENSGv'].apply(lambda x: len(x))
set_columns['count_stableID_key'] = set_columns['stableID_key'].apply(lambda x: len(x))
set_columns['count_proSequence'] = set_columns['proSequence'].apply(lambda x: len(x))

CPU times: user 1.71 s, sys: 2.43 ms, total: 1.71 s
Wall time: 1.71 s


In [33]:
set_columns.head(5)

ENSP  \
xref                                                        
A0AVT1                 {ENSP00000313454, ENSP00000399234}   
A0FGR8                                  {ENSP00000251527}   
A0JNW5  {ENSP00000279907, ENSP00000444824, ENSP0000034...   
A0MZ66  {ENSP00000260777, ENSP00000480109, ENSP0000034...   
A1KXE4                 {ENSP00000374565, ENSP00000387051}   

                                                    ENSPv  \
xref                                                        
A0AVT1             {ENSP00000313454.4, ENSP00000399234.2}   
A0FGR8             {ENSP00000251527.5, ENSP00000251527.6}   
A0JNW5  {ENSP00000349285.3, ENSP00000444824.2, ENSP000...   
A0MZ66  {ENSP00000480109.1, ENSP00000260777.10, ENSP00...   
A1KXE4             {ENSP00000374565.3, ENSP00000387051.1}   

                                                     ENST  \
xref                                                        
A0AVT1                 {ENST00000420827, ENST00000322244}   
A0FGR8                                  {ENST00000251527}   
A0JNW5  {ENST00000356828, ENST00000545232, ENST0000027...   
A0MZ66  {ENST00000615301, ENST00000392901, ENST0000035...   
A1KXE4                 {ENST00000389915, ENST00000409185}   

                                                    ENSTv               ENSG  \
xref                                                                           
A0AVT1  {ENST00000322244.10, ENST00000420827.2, ENST00...  {ENSG00000033178}   
A0FGR8  {ENST00000251527.5, ENST00000251527.10, ENST00...  {ENSG00000117868}   
A0JNW5  {ENST00000279907.12, ENST00000279907.11, ENST0...  {ENSG00000111647}   
A0MZ66  {ENST00000392901.10, ENST00000355371.9, ENST00...  {ENSG00000187164}   
A1KXE4  {ENST00000389915.3, ENST00000409185.1, ENST000...  {ENSG00000152102}   

                                                    ENSGv  \
xref                                                        
A0AVT1  {ENSG00000033178.8, ENSG00000033178.13, ENSG00...   
A0FGR8  {ENSG00000117868.11, ENSG00000117868.15, ENSG0...   
A0JNW5  {ENSG00000111647.8, ENSG00000111647.12, ENSG00...   
A0MZ66  {ENSG00000187164.19, ENSG00000187164.13, ENSG0...   
A1KXE4  {ENSG00000152102.17, ENSG00000152102.13, ENSG0...   

                                             stableID_key  \
xref                                                        
A0AVT1  {ENSG00000033178_ENST00000322244_ENSP000003134...   
A0FGR8  {ENSG00000117868_ENST00000251527_ENSP00000251527}   
A0JNW5  {ENSG00000111647_ENST00000279907_ENSP000002799...   
A0MZ66  {ENSG00000187164_ENST00000392901_ENSP000003766...   
A1KXE4  {ENSG00000152102_ENST00000389915_ENSP000003745...   

                                              proSequence  count_ENSP  \
xref                                                                    
A0AVT1  {MEGSEPVAAHQGEEASCSSWGTGSTNKNLPIMSTASVEIDDALYS...           2   
A0FGR8  {MSGARGEGPEAGAGGAGGRAAPENPGGVLSVELPGLLAQLARSFA...           1   
A0JNW5  {MQLSFTQLTIDYYPYHKAGDSCNHWMYFSDATKTKNGWANELLHE...           3   
A0MZ66  {MNSSDEEKQLQLITSLKEQAIGEYEDLRAENQKTKEKCDKIRQER...           5   
A1KXE4  {MNPVYSPGSSGVPYANAKGIGYPAGFPMGYAAAAPAYSPNMYPGA...           2   

        count_ENSPv  count_ENST  count_ENSTv  count_ENSG  count_ENSGv  \
xref                                                                    
A0AVT1            2           2            4           1            3   
A0FGR8            2           1            3           1            3   
A0JNW5            3           3            6           1            3   
A0MZ66            7           5           10           1            3   
A1KXE4            2           2            4           1            3   

        count_stableID_key  count_proSequence  
xref                                           
A0AVT1                   2                  2  
A0FGR8                   1                  2  
A0JNW5                   3                  3  
A0MZ66                   5                  6  
A1KXE4                   2              

In [34]:
%%time

# same number of rows and same number of IDs in each release

def setme(s):
    ls = list(s)
    finalset = set(ls)
    return finalset


# columns based on set of IDs or sequences from all releases
ENSP_share_3887 = share_3887.groupby('xref')['ENSP'].apply(setme)
ENSPv_share_3887 = share_3887.groupby('xref')['ENSPv'].apply(setme)
ENST_share_3887 = share_3887.groupby('xref')['ENST'].apply(setme)
ENSTv_share_3887 = share_3887.groupby('xref')['ENSTv'].apply(setme)
ENSG_share_3887 = share_3887.groupby('xref')['ENSG'].apply(setme)
ENSGv_share_3887 = share_3887.groupby('xref')['ENSGv'].apply(setme)
stableID_key_share_3887 = share_3887.groupby('xref')['stableID_key'].apply(setme)
proSequence_share_3887 = share_3887.groupby('xref')['proSequence'].apply(setme)

# concat
set_columns2 = pd.concat([ENSP_share_3887, ENSPv_share_3887, ENST_share_3887, ENSTv_share_3887, ENSG_share_3887, ENSGv_share_3887, stableID_key_share_3887, proSequence_share_3887], axis=1)

set_columns2['count_ENSP'] = set_columns2['ENSP'].apply(lambda x: len(x))
set_columns2['count_ENSPv'] = set_columns2['ENSPv'].apply(lambda x: len(x))
set_columns2['count_ENST'] = set_columns2['ENST'].apply(lambda x: len(x))
set_columns2['count_ENSTv'] = set_columns2['ENSTv'].apply(lambda x: len(x))
set_columns2['count_ENSG'] = set_columns2['ENSG'].apply(lambda x: len(x))
set_columns2['count_ENSGv'] = set_columns2['ENSGv'].apply(lambda x: len(x))
set_columns2['count_stableID_key'] = set_columns2['stableID_key'].apply(lambda x: len(x))
set_columns2['count_proSequence'] = set_columns2['proSequence'].apply(lambda x: len(x))

CPU times: user 1.79 s, sys: 4.89 ms, total: 1.8 s
Wall time: 1.8 s


In [35]:
set_columns2.head(5)

ENSP  \
xref                                                        
A0AVT1                 {ENSP00000313454, ENSP00000399234}   
A0FGR8                                  {ENSP00000251527}   
A0JNW5                 {ENSP00000279907, ENSP00000349285}   
A0MZ66  {ENSP00000376636, ENSP00000347532, ENSP0000026...   
A1KXE4                 {ENSP00000374565, ENSP00000387051}   

                                                    ENSPv  \
xref                                                        
A0AVT1             {ENSP00000313454.4, ENSP00000399234.2}   
A0FGR8             {ENSP00000251527.5, ENSP00000251527.6}   
A0JNW5             {ENSP00000349285.3, ENSP00000279907.7}   
A0MZ66  {ENSP00000260777.10, ENSP00000376636.3, ENSP00...   
A1KXE4             {ENSP00000374565.3, ENSP00000387051.1}   

                                                     ENST  \
xref                                                        
A0AVT1                 {ENST00000420827, ENST00000322244}   
A0FGR8                                  {ENST00000251527}   
A0JNW5                 {ENST00000356828, ENST00000279907}   
A0MZ66  {ENST00000355371, ENST00000392901, ENST0000026...   
A1KXE4                 {ENST00000389915, ENST00000409185}   

                                                    ENSTv               ENSG  \
xref                                                                           
A0AVT1  {ENST00000322244.10, ENST00000420827.2, ENST00...  {ENSG00000033178}   
A0FGR8  {ENST00000251527.5, ENST00000251527.10, ENST00...  {ENSG00000117868}   
A0JNW5  {ENST00000279907.12, ENST00000279907.11, ENST0...  {ENSG00000111647}   
A0MZ66  {ENST00000392901.10, ENST00000355371.9, ENST00...  {ENSG00000187164}   
A1KXE4  {ENST00000389915.3, ENST00000409185.1, ENST000...  {ENSG00000152102}   

                                                    ENSGv  \
xref                                                        
A0AVT1  {ENSG00000033178.8, ENSG00000033178.13, ENSG00...   
A0FGR8  {ENSG00000117868.11, ENSG00000117868.15, ENSG0...   
A0JNW5  {ENSG00000111647.8, ENSG00000111647.12, ENSG00...   
A0MZ66  {ENSG00000187164.19, ENSG00000187164.13, ENSG0...   
A1KXE4  {ENSG00000152102.17, ENSG00000152102.13, ENSG0...   

                                             stableID_key  \
xref                                                        
A0AVT1  {ENSG00000033178_ENST00000322244_ENSP000003134...   
A0FGR8  {ENSG00000117868_ENST00000251527_ENSP00000251527}   
A0JNW5  {ENSG00000111647_ENST00000279907_ENSP000002799...   
A0MZ66  {ENSG00000187164_ENST00000355371_ENSP000003475...   
A1KXE4  {ENSG00000152102_ENST00000389915_ENSP000003745...   

                                              proSequence  count_ENSP  \
xref                                                                    
A0AVT1  {MEGSEPVAAHQGEEASCSSWGTGSTNKNLPIMSTASVEIDDALYS...           2   
A0FGR8  {MSGARGEGPEAGAGGAGGRAAPENPGGVLSVELPGLLAQLARSFA...           1   
A0JNW5  {MAGIIKKQILKHLSRFTKNLSPDKINLSTLKGEGELKNLELDEEV...           2   
A0MZ66  {MNSSDEEKQLQLITSLKEQAIGEYEDLRAENQKTKEKCDKIRQER...           4   
A1KXE4  {MNPVYSPGSSGVPYANAKGIGYPAGFPMGYAAAAPAYSPNMYPGA...           2   

        count_ENSPv  count_ENST  count_ENSTv  count_ENSG  count_ENSGv  \
xref                                                                    
A0AVT1            2           2            4           1            3   
A0FGR8            2           1            3           1            3   
A0JNW5            2           2            5           1            3   
A0MZ66            6           4            9           1            3   
A1KXE4            2           2            4           1            3   

        count_stableID_key  count_proSequence  
xref                                           
A0AVT1                   2                  2  
A0FGR8                   1                  2  
A0JNW5                   2                  2  
A0MZ66                   4                  6  
A1KXE4                   2              

---
---

# should i do std of set of version IDs or List of version IDs?

### std from set of all values -StatisticsError: variance requires at least two data points

In [36]:
test = [4, 2, 4, 2, 4, 2, 4, 2, 4, 2]
set_test = {4, 2}
print(stdev(test))
print(stdev(set_test))

# list std smaller than set std

1.0540925533894598
1.4142135623730951


---

## create std frame from list of all values from releases in each 

In [37]:
# columns based on list of things NOT SET, for SD calculation
Length_all_3953 = all_3953.groupby('xref')['Length'].apply(list)
prov_all_3953 = all_3953.groupby('xref')['pro_ver'].apply(list)
txv_all_3953 = all_3953.groupby('xref')['tx_ver'].apply(list)
genv_all_3953 = all_3953.groupby('xref')['gen_ver'].apply(list)
# concat
list_columns = pd.concat([Length_all_3953, prov_all_3953, txv_all_3953, genv_all_3953], axis=1)
# creating column for number of ENSP ids
list_columns['stdev_length'] = list_columns['Length'].apply(lambda x: stdev(x))
list_columns['stdev_prov'] = list_columns['pro_ver'].apply(lambda x: stdev(x))
list_columns['stdev_txv'] = list_columns['tx_ver'].apply(lambda x: stdev(x))
list_columns['stdev_genv'] = list_columns['gen_ver'].apply(lambda x: stdev(x))

In [38]:
list_columns.head(5)

Length  \
xref                                                        
A0AVT1  [1052, 389, 1052, 389, 1052, 389, 1052, 389, 1...   
A0FGR8                          [893, 893, 893, 845, 845]   
A0JNW5  [1464, 522, 1114, 1464, 522, 1464, 522, 1464, ...   
A0MZ66  [456, 631, 498, 649, 571, 631, 498, 558, 456, ...   
A1KXE4  [195, 195, 195, 195, 195, 195, 195, 195, 195, ...   

                                                  pro_ver  \
xref                                                        
A0AVT1                     [4, 2, 4, 2, 4, 2, 4, 2, 4, 2]   
A0FGR8                                    [5, 5, 5, 6, 6]   
A0JNW5                  [7, 3, 2, 7, 3, 7, 3, 7, 3, 7, 3]   
A0MZ66  [10, 4, 4, 2, 11, 4, 4, 3, 1, 11, 4, 4, 3, 1, ...   
A1KXE4                     [3, 1, 3, 1, 3, 1, 3, 1, 3, 1]   

                                                   tx_ver  \
xref                                                        
A0AVT1                   [5, 2, 9, 2, 9, 2, 10, 2, 10, 2]   
A0FGR8                                  [5, 9, 9, 10, 10]   
A0JNW5              [7, 3, 2, 11, 7, 11, 7, 12, 7, 12, 7]   
A0MZ66  [10, 4, 4, 2, 14, 8, 10, 3, 4, 14, 8, 10, 3, 4...   
A1KXE4                     [3, 1, 3, 5, 3, 5, 4, 5, 4, 5]   

                                                  gen_ver  stdev_length  \
xref                                                                      
A0AVT1             [8, 8, 12, 12, 12, 12, 13, 13, 13, 13]    349.431681   
A0FGR8                               [11, 15, 15, 16, 16]     26.290683   
A0JNW5          [8, 8, 8, 12, 12, 12, 12, 13, 13, 13, 13]    472.410838   
A0MZ66  [13, 13, 13, 13, 19, 19, 19, 19, 19, 19, 19, 1...     66.535977   
A1KXE4           [13, 13, 17, 17, 17, 17, 18, 18, 18, 18]      0.000000   

        stdev_prov  stdev_txv  stdev_genv  
xref                                       
A0AVT1    1.054093   3.743142    1.955050  
A0FGR8    0.547723   2.073644    2.073644  
A0JNW5    2.195036   3.400535    2.148996  
A0MZ66    3.396503   4.116950    2.518051  
A1KXE4    1.054093   1.316561    1.955050

In [39]:
# version 3887
Length_share_3887 = share_3887.groupby('xref')['Length'].apply(list)
prov_share_3887 = share_3887.groupby('xref')['pro_ver'].apply(list)
txv_share_3887 = share_3887.groupby('xref')['tx_ver'].apply(list)
genv_share_3887 = share_3887.groupby('xref')['gen_ver'].apply(list)
# concat
list_columns2 = pd.concat([Length_share_3887, prov_share_3887, txv_share_3887, genv_share_3887], axis=1)
# creating column for number of ENSP ids
list_columns2['stdev_length'] = list_columns2['Length'].apply(lambda x: stdev(x))
list_columns2['stdev_prov'] = list_columns2['pro_ver'].apply(lambda x: stdev(x))
list_columns2['stdev_txv'] = list_columns2['tx_ver'].apply(lambda x: stdev(x))
list_columns2['stdev_genv'] = list_columns2['gen_ver'].apply(lambda x: stdev(x))

In [40]:
list_columns2.head(5)

Length  \
xref                                                        
A0AVT1  [1052, 389, 1052, 389, 1052, 389, 1052, 389, 1...   
A0FGR8                          [893, 893, 893, 845, 845]   
A0JNW5  [1464, 522, 1464, 522, 1464, 522, 1464, 522, 1...   
A0MZ66  [456, 631, 498, 649, 571, 631, 498, 558, 571, ...   
A1KXE4  [195, 195, 195, 195, 195, 195, 195, 195, 195, ...   

                                                  pro_ver  \
xref                                                        
A0AVT1                     [4, 2, 4, 2, 4, 2, 4, 2, 4, 2]   
A0FGR8                                    [5, 5, 5, 6, 6]   
A0JNW5                     [7, 3, 7, 3, 7, 3, 7, 3, 7, 3]   
A0MZ66  [10, 4, 4, 2, 11, 4, 4, 3, 11, 4, 4, 3, 11, 4,...   
A1KXE4                     [3, 1, 3, 1, 3, 1, 3, 1, 3, 1]   

                                                   tx_ver  \
xref                                                        
A0AVT1                   [5, 2, 9, 2, 9, 2, 10, 2, 10, 2]   
A0FGR8                                  [5, 9, 9, 10, 10]   
A0JNW5                 [7, 3, 11, 7, 11, 7, 12, 7, 12, 7]   
A0MZ66  [10, 4, 4, 2, 14, 8, 10, 3, 14, 8, 10, 3, 14, ...   
A1KXE4                     [3, 1, 3, 5, 3, 5, 4, 5, 4, 5]   

                                                  gen_ver  stdev_length  \
xref                                                                      
A0AVT1             [8, 8, 12, 12, 12, 12, 13, 13, 13, 13]    349.431681   
A0FGR8                               [11, 15, 15, 16, 16]     26.290683   
A0JNW5             [8, 8, 12, 12, 12, 12, 13, 13, 13, 13]    496.477593   
A0MZ66  [13, 13, 13, 13, 19, 19, 19, 19, 19, 19, 19, 1...     57.785538   
A1KXE4           [13, 13, 17, 17, 17, 17, 18, 18, 18, 18]      0.000000   

        stdev_prov  stdev_txv  stdev_genv  
xref                                       
A0AVT1    1.054093   3.743142    1.955050  
A0FGR8    0.547723   2.073644    2.073644  
A0JNW5    2.108185   2.951459    1.955050  
A0MZ66    3.250911   4.191470    2.706717  
A1KXE4    1.054093   1.316561    1.955050

# saving 3953 and 3887 files

In [11]:
print(list_columns.shape)
print(set_columns.shape)

set_columns.to_csv("ALL_releases_set_counts_ID_types_3953.csv")
list_columns.to_csv("ALL_releases_list_stdev_ID_versions_3953.csv")

(3953, 8)
(3953, 16)


In [10]:
print(list_columns2.shape)
print(set_columns2.shape)

set_columns2.to_csv("ALL_releases_set_counts_ID_types_3887.csv")
list_columns2.to_csv("ALL_releases_list_stdev_ID_versions_3887.csv")

(3887, 8)
(3887, 16)


In [18]:
v97share.sum()

ENSPv           ENSP00000363937.5ENSP00000363940.5ENSP00000363...
ENSP            ENSP00000363937ENSP00000363940ENSP00000363944E...
ENSTv           ENST00000374804.9ENST00000374807.9ENST00000374...
ENST            ENST00000374804ENST00000374807ENST00000374811E...
ENSGv           ENSG00000001497.16ENSG00000001497.16ENSG000000...
ENSG            ENSG00000001497ENSG00000001497ENSG00000001497E...
Length                                                    5136624
proSequence     MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...
stableID_key    ENSG00000001497_ENST00000374804_ENSP0000036393...
xref            Q9Y4W2Q9Y4W2Q9Y4W2Q9Y4W2O00522O00522O00522O005...
pro_ver                                                     25825
tx_ver                                                      59439
gen_ver                                                    123921
dtype: object

In [19]:
v96share.sum()

ENSPv           ENSP00000363937.5ENSP00000363940.5ENSP00000363...
ENSP            ENSP00000363937ENSP00000363940ENSP00000363944E...
ENSTv           ENST00000374804.9ENST00000374807.9ENST00000374...
ENST            ENST00000374804ENST00000374807ENST00000374811E...
ENSGv           ENSG00000001497.16ENSG00000001497.16ENSG000000...
ENSG            ENSG00000001497ENSG00000001497ENSG00000001497E...
Length                                                    5136967
proSequence     MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...
stableID_key    ENSG00000001497_ENST00000374804_ENSP0000036393...
xref            Q9Y4W2Q9Y4W2Q9Y4W2Q9Y4W2O00522O00522O00522O005...
pro_ver                                                     25814
tx_ver                                                      59400
gen_ver                                                    123607
dtype: object

In [20]:
v94share.sum()

ENSPv           ENSP00000363937.5ENSP00000363940.5ENSP00000363...
ENSP            ENSP00000363937ENSP00000363940ENSP00000363944E...
ENSTv           ENST00000374804.9ENST00000374807.9ENST00000374...
ENST            ENST00000374804ENST00000374807ENST00000374811E...
ENSGv           ENSG00000001497.16ENSG00000001497.16ENSG000000...
ENSG            ENSG00000001497ENSG00000001497ENSG00000001497E...
Length                                                    5140402
proSequence     MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...
stableID_key    ENSG00000001497_ENST00000374804_ENSP0000036393...
xref            Q9Y4W2Q9Y4W2Q9Y4W2Q9Y4W2O00522O00522O00522O005...
pro_ver                                                     25796
tx_ver                                                      56892
gen_ver                                                    118502
dtype: object

In [21]:
v92share.sum()

ENSPv           ENSP00000363937.5ENSP00000363940.5ENSP00000363...
ENSP            ENSP00000363937ENSP00000363940ENSP00000363944E...
ENSTv           ENST00000374804.9ENST00000374807.9ENST00000374...
ENST            ENST00000374804ENST00000374807ENST00000374811E...
ENSGv           ENSG00000001497.16ENSG00000001497.16ENSG000000...
ENSG            ENSG00000001497ENSG00000001497ENSG00000001497E...
Length                                                    5140432
proSequence     MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...
stableID_key    ENSG00000001497_ENST00000374804_ENSP0000036393...
xref            Q9Y4W2Q9Y4W2Q9Y4W2Q9Y4W2O00522O00522O00522O005...
pro_ver                                                     25795
tx_ver                                                      56852
gen_ver                                                    118092
dtype: object

In [22]:
v85share.sum()

ENSPv           ENSP00000363937.5ENSP00000363940.5ENSP00000363...
ENSP            ENSP00000363937ENSP00000363940ENSP00000363944E...
ENSTv           ENST00000374804.5ENST00000374807.5ENST00000374...
ENST            ENST00000374804ENST00000374807ENST00000374811E...
ENSGv           ENSG00000001497.12ENSG00000001497.12ENSG000000...
ENSG            ENSG00000001497ENSG00000001497ENSG00000001497E...
Length                                                    5144513
proSequence     MSWESGAGPGLGSQGMDLVWSAWYGKCVKGKGSLPLSAHGIVVAWL...
stableID_key    ENSG00000001497_ENST00000374804_ENSP0000036393...
xref            Q9Y4W2Q9Y4W2Q9Y4W2Q9Y4W2O00522O00522O00522O005...
pro_ver                                                     25697
tx_ver                                                      26490
gen_ver                                                     82482
dtype: object

In [26]:
v85[v85['xref'] == 'P11413']

ENSPv             ENSP              ENSTv             ENST  \
1788  ENSP00000358633.2  ENSP00000358633  ENST00000369620.2  ENST00000369620   
1789  ENSP00000377192.2  ENSP00000377192  ENST00000393562.2  ENST00000393562   
1790  ENSP00000377194.2  ENSP00000377194  ENST00000393564.2  ENST00000393564   
1791  ENSP00000471208.1  ENSP00000471208  ENST00000593787.1  ENST00000593787   
1792  ENSP00000470721.1  ENSP00000470721  ENST00000594771.1  ENST00000594771   
1793  ENSP00000469988.1  ENSP00000469988  ENST00000595441.1  ENST00000595441   

                   ENSGv             ENSG  Length  \
1788  ENSG00000160211.11  ENSG00000160211     561   
1789  ENSG00000160211.11  ENSG00000160211     545   
1790  ENSG00000160211.11  ENSG00000160211     515   
1791   ENSG00000269087.2  ENSG00000269087     515   
1792   ENSG00000269087.2  ENSG00000269087     545   
1793   ENSG00000269087.2  ENSG00000269087     561   

                                            proSequence  \
1788  MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKK...   
1789  MGRRGSAPGNGRTLRGCERGGRRRRSADSVMAEQVALSRTQVCGIL...   
1790  MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKK...   
1791  MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKK...   
1792  MGRRGSAPGNGRTLRGCERGGRRRRSADSVMAEQVALSRTQVCGIL...   
1793  MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKK...   

                                         stableID_key    xref  pro_ver  \
1788  ENSG00000160211_ENST00000369620_ENSP00000358633  P11413        2   
1789  ENSG00000160211_ENST00000393562_ENSP00000377192  P11413        2   
1790  ENSG00000160211_ENST00000393564_ENSP00000377194  P11413        2   
1791  ENSG00000269087_ENST00000593787_ENSP00000471208  P11413        1   
1792  ENSG00000269087_ENST00000594771_ENSP00000470721  P11413        1   
1793  ENSG00000269087_ENST00000595441_ENSP00000469988  P11413        1   

      tx_ver  gen_ver  
1788       2       11  
1789       2       11  
1790       2       11  
1791       1        2  
1792       1        2  
1793       1        2

In [27]:
v85share[v85share['xref'] == 'P11413']

ENSPv             ENSP              ENSTv             ENST  \
6001  ENSP00000358633.2  ENSP00000358633  ENST00000369620.2  ENST00000369620   
6002  ENSP00000377192.2  ENSP00000377192  ENST00000393562.2  ENST00000393562   
6003  ENSP00000377194.2  ENSP00000377194  ENST00000393564.2  ENST00000393564   

                   ENSGv             ENSG  Length  \
6001  ENSG00000160211.11  ENSG00000160211     561   
6002  ENSG00000160211.11  ENSG00000160211     545   
6003  ENSG00000160211.11  ENSG00000160211     515   

                                            proSequence  \
6001  MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKK...   
6002  MGRRGSAPGNGRTLRGCERGGRRRRSADSVMAEQVALSRTQVCGIL...   
6003  MAEQVALSRTQVCGILREELFQGDAFHQSDTHIFIIMGASGDLAKK...   

                                         stableID_key    xref  pro_ver  \
6001  ENSG00000160211_ENST00000369620_ENSP00000358633  P11413        2   
6002  ENSG00000160211_ENST00000393562_ENSP00000377192  P11413        2   
6003  ENSG00000160211_ENST00000393564_ENSP00000377194  P11413        2   

      tx_ver  gen_ver  
6001       2       11  
6002       2       11  
6003       2       11

In [45]:
set_columns.reset_index(inplace=True)

In [47]:
G6PD = set_columns[set_columns['xref'] == 'P11413']

In [49]:
G6PD.to_csv("G6PD_pulledFrom_3953groupby_set_IDcount.csv", index=False)

In [50]:
G6PD

xref                                               ENSP  \
661  P11413  {ENSP00000377194, ENSP00000469988, ENSP0000035...   

                                                 ENSPv  \
661  {ENSP00000358633.2, ENSP00000469988.1, ENSP000...   

                                                  ENST  \
661  {ENST00000595441, ENST00000594771, ENST0000039...   

                                                 ENSTv  \
661  {ENST00000595441.1, ENST00000393562.7, ENST000...   

                                   ENSG  \
661  {ENSG00000160211, ENSG00000269087}   

                                                 ENSGv  \
661  {ENSG00000160211.11, ENSG00000269087.2, ENSG00...   

                                          stableID_key  \
661  {ENSG00000160211_ENST00000393564_ENSP000003771...   

                                           proSequence  count_ENSP  \
661  {MGRRGSAPGNGRTLRGCERGGRRRRSADSVMAEQVALSRTQVCGI...           7   

     count_ENSPv  count_ENST  count_ENSTv  count_ENSG  count_ENSGv  \
661            8           7           13           2            5   

     count_stableID_key  count_proSequence  
661                   7                  3